import type { ColumnType } from '@/types';
import type { SheetTemplate } from './types';

/**
 * 캐릭터 관련 템플릿
 * RPG 캐릭터 스탯, MOBA 챔피언 등
 */
export const characterTemplates: SheetTemplate[] = [
  // RPG 캐릭터 스탯
  {
    id: 'rpg-character',
    name: '캐릭터스탯',
    description: '캐릭터별 기본 능력치와 역할에 따른 스탯 배분',
    category: 'character',
    genre: ['rpg'],
    context: '글로벌설정 시트의 BASE_HP, BASE_ATK, BASE_DEF를 참조하여 역할별 배율 적용',
    keyMetrics: [
      '탱커: 기준 대비 HP×1.5, DEF×3.0, ATK×0.8',
      '딜러: 기준 대비 ATK×2.0, HP×0.7, CritRate×5',
      '힐러: 기준값 유지, 힐량은 스킬 배율로 별도 조정',
    ],
    dependencies: [
      {
        templateId: 'global-config',
        sheetName: '글로벌설정',
        description: 'BASE_HP, BASE_ATK, BASE_DEF 값 참조',
      },
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '이름', type: 'general' as ColumnType, width: 100, exportName: 'name' },
      { name: '등급', type: 'general' as ColumnType, width: 60, exportName: 'grade' },
      { name: '역할', type: 'general' as ColumnType, width: 70, exportName: 'role' },
      { name: 'HP배율', type: 'general' as ColumnType, width: 70, exportName: 'hpMultiplier' },
      { name: 'HP', type: 'formula' as ColumnType, width: 90, exportName: 'hp' },
      { name: 'ATK배율', type: 'general' as ColumnType, width: 75, exportName: 'atkMultiplier' },
      { name: 'ATK', type: 'formula' as ColumnType, width: 90, exportName: 'atk' },
      { name: 'DEF배율', type: 'general' as ColumnType, width: 75, exportName: 'defMultiplier' },
      { name: 'DEF', type: 'formula' as ColumnType, width: 90, exportName: 'def' },
      { name: 'CritRate', type: 'general' as ColumnType, width: 75, exportName: 'critRate' },
      { name: 'CritDMG', type: 'general' as ColumnType, width: 75, exportName: 'critDmg' },
      { name: 'EHP', type: 'formula' as ColumnType, width: 90, exportExcluded: true },
      { name: 'DPS', type: 'formula' as ColumnType, width: 90, exportExcluded: true },
      { name: '설계의도', type: 'general' as ColumnType, width: 280, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'CHAR_001',
          col1: '철갑 기사',
          col2: 'SSR',
          col3: '탱커',
          col4: 1.5,
          col5: '=글로벌설정.BASE_HP*HP배율',
          col6: 0.8,
          col7: '=글로벌설정.BASE_ATK*ATK배율',
          col8: 3.0,
          col9: '=글로벌설정.BASE_DEF*DEF배율',
          col10: 0.05,
          col11: 1.5,
          col12: '=HP*(1+DEF/100)',
          col13: '=ATK*(1+CritRate*(CritDMG-1))',
          col14: 'HP=BASE×1.5, DEF=BASE×3 → EHP=HP×(1+DEF/100). DPS=ATK×(1+Crit×(CritDMG-1))',
        },
      },
      {
        cells: {
          col0: 'CHAR_002',
          col1: '암살자',
          col2: 'SSR',
          col3: '딜러',
          col4: 0.7,
          col5: '=글로벌설정.BASE_HP*HP배율',
          col6: 2.0,
          col7: '=글로벌설정.BASE_ATK*ATK배율',
          col8: 0.8,
          col9: '=글로벌설정.BASE_DEF*DEF배율',
          col10: 0.25,
          col11: 2.0,
          col12: '=HP*(1+DEF/100)',
          col13: '=ATK*(1+CritRate*(CritDMG-1))',
          col14: 'HP 낮음, DEF 낮음 → EHP 낮음. ATK 높음, Crit 25%×2배 → 고위험 고화력',
        },
      },
      {
        cells: {
          col0: 'CHAR_003',
          col1: '사제',
          col2: 'SR',
          col3: '힐러',
          col4: 1.0,
          col5: '=글로벌설정.BASE_HP*HP배율',
          col6: 0.6,
          col7: '=글로벌설정.BASE_ATK*ATK배율',
          col8: 1.4,
          col9: '=글로벌설정.BASE_DEF*DEF배율',
          col10: 0.1,
          col11: 1.5,
          col12: '=HP*(1+DEF/100)',
          col13: '=ATK*(1+CritRate*(CritDMG-1))',
          col14: '중간 생존력. 힐량=ATK×스킬배율로 별도 계산',
        },
      },
      {
        cells: {
          col0: 'CHAR_004',
          col1: '마법사',
          col2: 'SR',
          col3: '딜러',
          col4: 0.8,
          col5: '=글로벌설정.BASE_HP*HP배율',
          col6: 1.5,
          col7: '=글로벌설정.BASE_ATK*ATK배율',
          col8: 0.9,
          col9: '=글로벌설정.BASE_DEF*DEF배율',
          col10: 0.15,
          col11: 1.8,
          col12: '=HP*(1+DEF/100)',
          col13: '=ATK*(1+CritRate*(CritDMG-1))',
          col14: '암살자 대비 낮은 DPS지만 범위기로 총 딜 보상',
        },
      },
    ],
  },

  // MOBA 챔피언 설계
  {
    id: 'moba-champion',
    name: '챔피언스탯',
    description: '챔피언 기본 스탯과 레벨당 성장. 역할별 스케일링 차등.',
    category: 'character',
    genre: ['moba'],
    context: '18레벨 기준 밸런스. 초반 강캐 vs 후반 강캐 설계',
    keyMetrics: [
      '초반형: 높은 기본값, 낮은 성장률 (초반 우위)',
      '후반형: 낮은 기본값, 높은 성장률 (후반 강세)',
      '레벨18 기준 총 스탯 유사하게 조정',
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '챔피언명', type: 'general' as ColumnType, width: 100, exportName: 'championName' },
      { name: '역할', type: 'general' as ColumnType, width: 70, exportName: 'role' },
      { name: '타입', type: 'general' as ColumnType, width: 65, exportName: 'type' },
      { name: 'HP(1렙)', type: 'general' as ColumnType, width: 80, exportName: 'baseHp' },
      { name: 'HP성장', type: 'general' as ColumnType, width: 75, exportName: 'hpGrowth' },
      { name: 'HP(18렙)', type: 'formula' as ColumnType, width: 90, exportName: 'maxHp' },
      { name: 'AD(1렙)', type: 'general' as ColumnType, width: 75, exportName: 'baseAd' },
      { name: 'AD성장', type: 'general' as ColumnType, width: 75, exportName: 'adGrowth' },
      { name: 'AD(18렙)', type: 'formula' as ColumnType, width: 85, exportName: 'maxAd' },
      { name: '설계의도', type: 'general' as ColumnType, width: 250, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'CHMP_001',
          col1: '전사',
          col2: '파이터',
          col3: '후반형',
          col4: 580,
          col5: 95,
          col6: '=HP(1렙)+HP성장*17',
          col7: 60,
          col8: 3.5,
          col9: '=AD(1렙)+AD성장*17',
          col10: 'HP 2195, AD 120 @18렙. 후반 탱딜 역할',
        },
      },
      {
        cells: {
          col0: 'CHMP_002',
          col1: '마법사',
          col2: '메이지',
          col3: '중립',
          col4: 520,
          col5: 80,
          col6: '=HP(1렙)+HP성장*17',
          col7: 52,
          col8: 2.5,
          col9: '=AD(1렙)+AD성장*17',
          col10: 'HP 1880, AD 95 @18렙. AP 스케일링이 본체',
        },
      },
      {
        cells: {
          col0: 'CHMP_003',
          col1: '저격수',
          col2: '원거리딜',
          col3: '후반형',
          col4: 500,
          col5: 85,
          col6: '=HP(1렙)+HP성장*17',
          col7: 58,
          col8: 4.0,
          col9: '=AD(1렙)+AD성장*17',
          col10: 'HP 1945, AD 126 @18렙. 최고 AD 성장. 후반 캐리',
        },
      },
      {
        cells: {
          col0: 'CHMP_004',
          col1: '암살자',
          col2: '어쌔신',
          col3: '초반형',
          col4: 600,
          col5: 70,
          col6: '=HP(1렙)+HP성장*17',
          col7: 68,
          col8: 2.0,
          col9: '=AD(1렙)+AD성장*17',
          col10: 'HP 1790, AD 102 @18렙. 높은 초반 AD. 스노우볼',
        },
      },
    ],
  },
];
