import type { ColumnType } from '@/types';
import type { SheetTemplate } from './types';

/**
 * 전투 관련 템플릿
 * 스킬, 장비, 몬스터, FPS 무기 등
 */
export const combatTemplates: SheetTemplate[] = [
  // 스킬 데이터
  {
    id: 'rpg-skill',
    name: '스킬데이터',
    description: '스킬 배율과 쿨타임 설계. DPS 균형을 위한 배율/쿨타임 트레이드오프.',
    category: 'skill',
    genre: ['rpg', 'action', 'moba'],
    context: '스킬 DPS ≈ 평타 DPS × 1.3 유지. 스킬이 강하되 평타도 의미있게',
    keyMetrics: [
      '기대 DPS = 배율 × (1/쿨타임)',
      '강한 스킬 = 높은 배율 + 긴 쿨타임',
      '유틸 스킬 = 낮은 배율 + 짧은 쿨타임 + CC효과',
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '스킬명', type: 'general' as ColumnType, width: 110, exportName: 'skillName' },
      { name: '타입', type: 'general' as ColumnType, width: 70, exportName: 'type' },
      { name: '배율(%)', type: 'general' as ColumnType, width: 75, exportName: 'multiplier' },
      { name: '쿨타임(s)', type: 'general' as ColumnType, width: 80, exportName: 'cooldown' },
      { name: '마나', type: 'general' as ColumnType, width: 60, exportName: 'manaCost' },
      { name: '대상수', type: 'general' as ColumnType, width: 65, exportName: 'targetCount' },
      { name: '스킬DPS', type: 'formula' as ColumnType, width: 90, exportName: 'skillDps' },
      { name: '효과', type: 'general' as ColumnType, width: 120, exportName: 'effect' },
      { name: '설계의도', type: 'general' as ColumnType, width: 250, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'SKL_001',
          col1: '강타',
          col2: '액티브',
          col3: 200,
          col4: 6,
          col5: 20,
          col6: 1,
          col7: '=배율(%)/100/쿨타임(s)',
          col8: '없음',
          col9: 'DPS 0.33. 평타(DPS 1.0)의 33% 추가딜. 단일 대상 주력기',
        },
      },
      {
        cells: {
          col0: 'SKL_002',
          col1: '회오리베기',
          col2: '액티브',
          col3: 120,
          col4: 10,
          col5: 40,
          col6: 5,
          col7: '=배율(%)/100/쿨타임(s)*대상수',
          col8: '없음',
          col9: 'DPS 0.12×5=0.6. 다중 타겟으로 단일기보다 총 딜 높음',
        },
      },
      {
        cells: {
          col0: 'SKL_003',
          col1: '궁극기',
          col2: '궁극',
          col3: 500,
          col4: 60,
          col5: 100,
          col6: 3,
          col7: '=배율(%)/100/쿨타임(s)*대상수',
          col8: '기절 2초',
          col9: 'DPS 0.25. 60초 쿨이지만 전투당 1회로 결정적 순간용',
        },
      },
      {
        cells: {
          col0: 'SKL_004',
          col1: '도발',
          col2: '유틸',
          col3: 0,
          col4: 15,
          col5: 30,
          col6: 0,
          col7: 0,
          col8: '어그로 5초',
          col9: '딜 없음. 탱커 필수 유틸. 어그로 지속시간/쿨타임 비율 33%',
        },
      },
    ],
  },

  // 장비 데이터
  {
    id: 'rpg-equipment',
    name: '장비스탯',
    description: '장비 등급별 스탯 설계. 기준값 = BASE_ATK의 30%(무기), BASE_DEF의 80%(방어구)',
    category: 'equipment',
    genre: ['rpg', 'action'],
    context: '장비 1개 = 기본 스탯의 30~50% 증가 목표. 6슬롯 풀장비 시 기본 대비 2배',
    keyMetrics: [
      '등급 배율: C(1.0) → B(1.5) → A(2.25) → S(3.4) → SS(5.0). 등급당 1.5배',
      '무기 기준값 30 = BASE_ATK(100)의 30%. 6슬롯 C급 풀장비 시 ATK +180(180%)',
      'SS급 1개(150) ≈ C급 5개(150). 획득 난이도로 밸런스',
    ],
    dependencies: [
      {
        templateId: 'global-config',
        sheetName: '글로벌설정',
        description: '기준값 산출에 BASE_ATK, BASE_DEF 참조',
      },
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '이름', type: 'general' as ColumnType, width: 110, exportName: 'name' },
      { name: '타입', type: 'general' as ColumnType, width: 65, exportName: 'type' },
      { name: '등급', type: 'general' as ColumnType, width: 50, exportName: 'grade' },
      { name: '등급배율', type: 'general' as ColumnType, width: 75, exportName: 'gradeMultiplier' },
      { name: '기준값', type: 'general' as ColumnType, width: 70, exportName: 'baseValue' },
      { name: '기준값근거', type: 'general' as ColumnType, width: 150, exportExcluded: true },
      { name: '주스탯', type: 'general' as ColumnType, width: 65, exportName: 'primaryStat' },
      { name: '주스탯값', type: 'formula' as ColumnType, width: 90, exportName: 'primaryStatValue' },
      { name: '부스탯', type: 'general' as ColumnType, width: 65, exportName: 'secondaryStat' },
      { name: '부스탯값', type: 'formula' as ColumnType, width: 90, exportName: 'secondaryStatValue' },
      { name: '설계의도', type: 'general' as ColumnType, width: 280, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'EQP_001',
          col1: '낡은 검',
          col2: '무기',
          col3: 'C',
          col4: 1.0,
          col5: 30,
          col6: 'BASE_ATK(100)×0.3',
          col7: 'ATK',
          col8: '=기준값*등급배율',
          col9: '',
          col10: 0,
          col11: '초반 장비. ATK 30으로 캐릭터 공격력 30% 증가. 부스탯 없음',
        },
      },
      {
        cells: {
          col0: 'EQP_002',
          col1: '강철검',
          col2: '무기',
          col3: 'B',
          col4: 1.5,
          col5: 30,
          col6: 'BASE_ATK(100)×0.3',
          col7: 'ATK',
          col8: '=기준값*등급배율',
          col9: 'CritRate',
          col10: '=0.03*등급배율',
          col11: 'ATK 45(+50%), CritRate 4.5%. C급 대비 체감 상승. 빌드 분화 시작',
        },
      },
      {
        cells: {
          col0: 'EQP_003',
          col1: '미스릴 갑옷',
          col2: '갑옷',
          col3: 'A',
          col4: 2.25,
          col5: 40,
          col6: 'BASE_DEF(50)×0.8',
          col7: 'DEF',
          col8: '=기준값*등급배율',
          col9: 'HP',
          col10: '=100*등급배율',
          col11: 'DEF 90, HP 225. 탱커 EHP 3750→5800(+55%). 생존력 대폭 상승',
        },
      },
      {
        cells: {
          col0: 'EQP_004',
          col1: '전설의 검',
          col2: '무기',
          col3: 'SS',
          col4: 5.0,
          col5: 30,
          col6: 'BASE_ATK(100)×0.3',
          col7: 'ATK',
          col8: '=기준값*등급배율',
          col9: 'CritDMG',
          col10: '=0.2*등급배율',
          col11: 'ATK 150(C급의 5배), CritDMG +100%. 드랍율 0.1%로 희소성 밸런스',
        },
      },
    ],
  },

  // 몬스터/적 데이터
  {
    id: 'rpg-monster',
    name: '몬스터데이터',
    description: '몬스터 스탯과 보상. 플레이어 레벨 기준 상대적 난이도 설계.',
    category: 'enemy',
    genre: ['rpg', 'action', 'roguelike'],
    context: '동레벨 플레이어 기준 TTK 5초, 피격 5회 사망 목표',
    keyMetrics: [
      '일반: 플레이어의 50% 스탯. EXP 10(2렙까지 10마리=100EXP)',
      '엘리트: 플레이어의 150% 스탯. EXP 50(일반의 5배, TTK 5배)',
      '보스: 플레이어의 500% HP. EXP 500(일반의 50배, 주간 1회 가치)',
    ],
    dependencies: [
      {
        templateId: 'global-config',
        sheetName: '글로벌설정',
        description: 'BASE_HP, BASE_ATK, GROWTH_RATE 값 참조',
      },
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '이름', type: 'general' as ColumnType, width: 100, exportName: 'name' },
      { name: '타입', type: 'general' as ColumnType, width: 60, exportName: 'type' },
      { name: '레벨', type: 'general' as ColumnType, width: 55, exportName: 'level' },
      { name: 'HP배율', type: 'general' as ColumnType, width: 70, exportName: 'hpMultiplier' },
      { name: 'HP', type: 'formula' as ColumnType, width: 100, exportName: 'hp' },
      { name: 'ATK배율', type: 'general' as ColumnType, width: 75, exportName: 'atkMultiplier' },
      { name: 'ATK', type: 'formula' as ColumnType, width: 90, exportName: 'atk' },
      { name: 'DEF', type: 'formula' as ColumnType, width: 80, exportName: 'def' },
      { name: 'EXP기준', type: 'general' as ColumnType, width: 75, exportName: 'baseExp' },
      { name: 'EXP', type: 'formula' as ColumnType, width: 90, exportName: 'exp' },
      { name: '골드기준', type: 'general' as ColumnType, width: 75, exportName: 'baseGold' },
      { name: '골드', type: 'formula' as ColumnType, width: 90, exportName: 'gold' },
      { name: 'TTK목표', type: 'general' as ColumnType, width: 70, exportExcluded: true },
      { name: '설계의도', type: 'general' as ColumnType, width: 280, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'MON_001',
          col1: '슬라임',
          col2: '일반',
          col3: 1,
          col4: 0.5,
          col5: '=글로벌설정.BASE_HP*HP배율*POWER(1.08,레벨-1)',
          col6: 0.5,
          col7: '=글로벌설정.BASE_ATK*ATK배율*POWER(1.08,레벨-1)',
          col8: '=SCALE(20, 레벨, 1.08, "exponential")',
          col9: 10,
          col10: '=EXP기준*POWER(1.08,레벨-1)',
          col11: 5,
          col12: '=골드기준*POWER(1.08,레벨-1)',
          col13: 3,
          col14: 'HP 500(BASE×0.5). EXP 10: 2렙필요EXP 100÷10=10마리. 50초 내 레벨업',
        },
      },
      {
        cells: {
          col0: 'MON_002',
          col1: '고블린 워리어',
          col2: '일반',
          col3: 5,
          col4: 0.5,
          col5: '=글로벌설정.BASE_HP*HP배율*POWER(1.08,레벨-1)',
          col6: 0.5,
          col7: '=글로벌설정.BASE_ATK*ATK배율*POWER(1.08,레벨-1)',
          col8: '=SCALE(20, 레벨, 1.08, "exponential")',
          col9: 10,
          col10: '=EXP기준*POWER(1.08,레벨-1)',
          col11: 5,
          col12: '=골드기준*POWER(1.08,레벨-1)',
          col13: 4,
          col14: '5렙 일반몹. HP 680(500×1.08^4). EXP 14(10×1.08^4). 레벨 스케일링 적용',
        },
      },
      {
        cells: {
          col0: 'MON_003',
          col1: '오크 대장',
          col2: '엘리트',
          col3: 5,
          col4: 1.5,
          col5: '=글로벌설정.BASE_HP*HP배율*POWER(1.08,레벨-1)',
          col6: 1.5,
          col7: '=글로벌설정.BASE_ATK*ATK배율*POWER(1.08,레벨-1)',
          col8: '=SCALE(60, 레벨, 1.08, "exponential")',
          col9: 50,
          col10: '=EXP기준*POWER(1.08,레벨-1)',
          col11: 30,
          col12: '=골드기준*POWER(1.08,레벨-1)',
          col13: 15,
          col14: 'HP 2040(BASE×1.5×1.08^4). EXP 50: 일반 5배. TTK 15초÷5초=3배 시간, 5배 보상으로 효율 유도',
        },
      },
      {
        cells: {
          col0: 'MON_004',
          col1: '드래곤',
          col2: '보스',
          col3: 10,
          col4: 5.0,
          col5: '=글로벌설정.BASE_HP*HP배율*POWER(1.08,레벨-1)',
          col6: 2.0,
          col7: '=글로벌설정.BASE_ATK*ATK배율*POWER(1.08,레벨-1)',
          col8: '=SCALE(100, 레벨, 1.08, "exponential")',
          col9: 500,
          col10: '=EXP기준*POWER(1.08,레벨-1)',
          col11: 300,
          col12: '=골드기준*POWER(1.08,레벨-1)',
          col13: 60,
          col14: 'HP 10,795(BASE×5×1.08^9). EXP 500: 일반 50배. 1분 보스전, 4인파티(DPS×4) 기준 TTK 15초',
        },
      },
    ],
  },

  // FPS 무기 데이터
  {
    id: 'fps-weapon',
    name: '무기스탯',
    description: 'FPS 무기 밸런스. TTK 기준으로 DPS와 정확도 트레이드오프.',
    category: 'equipment',
    genre: ['fps'],
    context: 'TTK 0.3~1.5초 권장. 무기별 역할 구분 명확히',
    keyMetrics: [
      '이론 TTK = 적HP / DPS',
      '실제 TTK = 이론TTK / 명중률',
      'DPS = 데미지 × (RPM/60)',
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '무기명', type: 'general' as ColumnType, width: 110, exportName: 'weaponName' },
      { name: '타입', type: 'general' as ColumnType, width: 80, exportName: 'type' },
      { name: '데미지', type: 'general' as ColumnType, width: 70, exportName: 'damage' },
      { name: 'RPM', type: 'general' as ColumnType, width: 65, exportName: 'rpm' },
      { name: '탄창', type: 'general' as ColumnType, width: 55, exportName: 'magazineSize' },
      { name: '재장전(s)', type: 'general' as ColumnType, width: 80, exportName: 'reloadTime' },
      { name: 'DPS', type: 'formula' as ColumnType, width: 80, exportName: 'dps' },
      { name: 'TTK(100HP)', type: 'formula' as ColumnType, width: 100, exportName: 'ttk' },
      { name: '역할', type: 'general' as ColumnType, width: 100, exportName: 'role' },
      { name: '설계의도', type: 'general' as ColumnType, width: 250, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'WPN_001',
          col1: 'M4A1',
          col2: '돌격소총',
          col3: 28,
          col4: 700,
          col5: 30,
          col6: 2.5,
          col7: '=데미지*RPM/60',
          col8: '=100/DPS',
          col9: '범용',
          col10: 'DPS 327, TTK 0.31초. 모든 거리에서 안정적. 기준 무기',
        },
      },
      {
        cells: {
          col0: 'WPN_002',
          col1: 'AK-47',
          col2: '돌격소총',
          col3: 35,
          col4: 600,
          col5: 30,
          col6: 2.7,
          col7: '=데미지*RPM/60',
          col8: '=100/DPS',
          col9: '고데미지',
          col10: 'DPS 350, TTK 0.29초. M4 대비 높은 반동. 리스크-리워드',
        },
      },
      {
        cells: {
          col0: 'WPN_003',
          col1: 'AWP',
          col2: '저격소총',
          col3: 115,
          col4: 41,
          col5: 5,
          col6: 3.5,
          col7: '=데미지*RPM/60',
          col8: '=100/DPS',
          col9: '원샷원킬',
          col10: 'DPS 79. 낮은 DPS지만 115 데미지로 헤드샷 원킬. 고스킬 무기',
        },
      },
      {
        cells: {
          col0: 'WPN_004',
          col1: 'MP5',
          col2: 'SMG',
          col3: 22,
          col4: 800,
          col5: 30,
          col6: 2.0,
          col7: '=데미지*RPM/60',
          col8: '=100/DPS',
          col9: '근접전',
          col10: 'DPS 293, TTK 0.34초. 낮은 데미지 but 빠른 연사. 근거리 특화',
        },
      },
    ],
  },
];
