import type { ColumnType } from '@/types';
import type { SheetTemplate } from './types';

/**
 * 콘텐츠 관련 템플릿
 * 스테이지, 유물, 카드, 드랍 테이블 등
 */
export const contentTemplates: SheetTemplate[] = [
  // 스테이지/웨이브 구성
  {
    id: 'td-wave',
    name: '웨이브구성',
    description: '웨이브별 난이도 스케일링. 플로우 이론 기반 난이도 곡선.',
    category: 'stage',
    genre: ['strategy', 'idle', 'roguelike'],
    context: '웨이브당 5~15% 난이도 증가. 10웨이브마다 보스로 긴장감',
    keyMetrics: [
      '난이도 = HP배율 × 수량',
      '보스 웨이브 = 일반의 5배 난이도',
      '휴식 구간(상점) = 10웨이브마다',
    ],
    dependencies: [
      {
        templateId: 'rpg-monster',
        sheetName: '몬스터데이터',
        description: '적ID 참조 (ENM_001, ENM_BOSS 등)',
      },
    ],
    columns: [
      { name: '웨이브', type: 'general' as ColumnType, width: 65, exportName: 'wave' },
      { name: '타입', type: 'general' as ColumnType, width: 70, exportName: 'type' },
      { name: '적ID', type: 'general' as ColumnType, width: 80, exportName: 'enemyId' },
      { name: '수량', type: 'formula' as ColumnType, width: 70, exportName: 'count' },
      { name: 'HP배율', type: 'formula' as ColumnType, width: 80, exportName: 'hpMultiplier' },
      { name: '난이도지수', type: 'formula' as ColumnType, width: 95, exportName: 'difficultyIndex' },
      { name: '보상골드', type: 'formula' as ColumnType, width: 90, exportName: 'rewardGold' },
      { name: '설계의도', type: 'general' as ColumnType, width: 250, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 1,
          col1: '일반',
          col2: 'ENM_001',
          col3: 5,
          col4: 1.0,
          col5: '=수량*HP배율',
          col6: 50,
          col7: '난이도 5. 워밍업. 시스템 이해',
        },
      },
      {
        cells: {
          col0: 5,
          col1: '일반',
          col2: 'ENM_001',
          col3: '=SCALE(5, 웨이브, 1.1, "exponential")',
          col4: '=SCALE(1, 웨이브, 1.05, "exponential")',
          col5: '=수량*HP배율',
          col6: '=SCALE(50, 웨이브, 1.1, "exponential")',
          col7: '난이도 10. 수량+HP 동시 스케일링',
        },
      },
      {
        cells: {
          col0: 10,
          col1: '보스',
          col2: 'ENM_BOSS',
          col3: 1,
          col4: '=SCALE(5, 웨이브/10, 1.5, "exponential")',
          col5: '=수량*HP배율',
          col6: '=SCALE(500, 웨이브, 1.15, "exponential")',
          col7: '첫 보스. 난이도 급상승. 패턴 학습 요구',
        },
      },
      {
        cells: {
          col0: 15,
          col1: '상점',
          col2: '-',
          col3: 0,
          col4: 0,
          col5: 0,
          col6: 0,
          col7: '휴식 구간. 업그레이드 선택. 플로우 조절',
        },
      },
      {
        cells: {
          col0: 20,
          col1: '보스',
          col2: 'ENM_BOSS',
          col3: 1,
          col4: '=SCALE(5, 웨이브/10, 1.5, "exponential")',
          col5: '=수량*HP배율',
          col6: '=SCALE(500, 웨이브, 1.15, "exponential")',
          col7: '2번째 보스. 첫 보스 대비 2.25배 HP',
        },
      },
    ],
  },

  // 로그라이크 유물/시너지
  {
    id: 'roguelike-relic',
    name: '유물시스템',
    description: '유물 효과와 시너지 설계. 빌드 다양성과 파워 스파이크.',
    category: 'item',
    genre: ['roguelike', 'card'],
    context: '유물 1개 = 전투력 10~20% 증가. 시너지 시 추가 보너스',
    keyMetrics: [
      '등급별 효과: 커먼 10%, 레어 20%, 에픽 35% (1.5배씩 증가)',
      '10개 제한: 최대 커먼풀 100%, 레어풀 200%, 에픽풀 350%',
      '시너지 보너스 50%: 3개 조합 시 1.5배 → 빌드 방향성 유도',
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '이름', type: 'general' as ColumnType, width: 110, exportName: 'name' },
      { name: '등급', type: 'general' as ColumnType, width: 60, exportName: 'grade' },
      { name: '등급배율', type: 'general' as ColumnType, width: 80, exportName: 'gradeMultiplier' },
      { name: '효과타입', type: 'general' as ColumnType, width: 90, exportName: 'effectType' },
      { name: '효과값', type: 'formula' as ColumnType, width: 100, exportName: 'effectValue' },
      { name: '효과근거', type: 'general' as ColumnType, width: 150, exportName: 'effectNote' },
      { name: '시너지태그', type: 'general' as ColumnType, width: 80, exportName: 'synergyTag' },
      { name: '시너지조건', type: 'general' as ColumnType, width: 90, exportName: 'synergyCondition' },
      { name: '시너지효과', type: 'general' as ColumnType, width: 130, exportName: 'synergyEffect' },
      { name: '설계의도', type: 'general' as ColumnType, width: 220, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'REL_001',
          col1: '낡은 장갑',
          col2: '커먼',
          col3: 0.1,
          col4: 'ATK증가',
          col5: '=등급배율',
          col6: '커먼 기준 10%',
          col7: '전사',
          col8: '전사 3개',
          col9: 'ATK +15% 추가',
          col10: '10%+시너지15%=25%. 커먼 3개로 에픽급 효과',
        },
      },
      {
        cells: {
          col0: 'REL_002',
          col1: '뱀파이어 송곳니',
          col2: '레어',
          col3: 0.2,
          col4: '흡혈',
          col5: '=등급배율*0.5',
          col6: '레어 20%×0.5(흡혈밸런스)',
          col7: '생존',
          col8: '생존 2개',
          col9: '흡혈 +5% 추가',
          col10: '흡혈 10%+시너지5%=15%. DPS 100기준 초당15HP 회복',
        },
      },
      {
        cells: {
          col0: 'REL_003',
          col1: '분노의 가면',
          col2: '에픽',
          col3: 0.35,
          col4: 'ATK증가',
          col5: '=등급배율',
          col6: '에픽 기준 35%',
          col7: '광전사',
          col8: 'HP 50% 이하',
          col9: 'ATK 2배',
          col10: '35%×2=70%. 조건부지만 에픽2개급 효과',
        },
      },
      {
        cells: {
          col0: 'REL_004',
          col1: '시간의 모래',
          col2: '에픽',
          col3: 0.35,
          col4: '쿨타임감소',
          col5: '=등급배율*0.7',
          col6: '에픽 35%×0.7(쿨감밸런스)',
          col7: '마법사',
          col8: '마법사 3개',
          col9: '추가 15% 감소',
          col10: '25%+시너지15%=40%. 쿨10초→6초. DPS 1.67배',
        },
      },
    ],
  },

  // 카드 게임 덱 설계
  {
    id: 'card-deck',
    name: '카드밸런스',
    description: '카드 코스트 대비 효율. 마나 커브와 카드 가치 설계.',
    category: 'card',
    genre: ['card', 'roguelike'],
    context: '1코스트당 효율 동일. 고코스트는 추가 효과로 가치 차등',
    keyMetrics: [
      '기본 효율: 1코스트 = 6데미지 or 5방어',
      '고코스트 보너스: 3코스트 이상 +10% 효율',
      '0코스트 카드는 효과 50%로 페널티',
    ],
    columns: [
      { name: 'ID', type: 'general' as ColumnType, width: 80, exportName: 'id' },
      { name: '카드명', type: 'general' as ColumnType, width: 110, exportName: 'cardName' },
      { name: '등급', type: 'general' as ColumnType, width: 60, exportName: 'grade' },
      { name: '타입', type: 'general' as ColumnType, width: 65, exportName: 'type' },
      { name: '코스트', type: 'general' as ColumnType, width: 60, exportName: 'cost' },
      { name: '데미지', type: 'general' as ColumnType, width: 65, exportName: 'damage' },
      { name: '방어도', type: 'general' as ColumnType, width: 65, exportName: 'block' },
      { name: '효율', type: 'formula' as ColumnType, width: 75, exportName: 'efficiency' },
      { name: '추가효과', type: 'general' as ColumnType, width: 130, exportName: 'additionalEffect' },
      { name: '설계의도', type: 'general' as ColumnType, width: 230, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: 'CRD_001',
          col1: '타격',
          col2: '기본',
          col3: '공격',
          col4: 1,
          col5: 6,
          col6: 0,
          col7: '=데미지/코스트',
          col8: '없음',
          col9: '효율 6.0. 기준 카드. 업그레이드 시 9데미지',
        },
      },
      {
        cells: {
          col0: 'CRD_002',
          col1: '수비',
          col2: '기본',
          col3: '스킬',
          col4: 1,
          col5: 0,
          col6: 5,
          col7: '=방어도/코스트',
          col8: '없음',
          col9: '효율 5.0. 방어는 데미지보다 약간 낮게 설계',
        },
      },
      {
        cells: {
          col0: 'CRD_003',
          col1: '분노의 일격',
          col2: '언커먼',
          col3: '공격',
          col4: 2,
          col5: 14,
          col6: 0,
          col7: '=데미지/코스트',
          col8: '취약 1',
          col9: '효율 7.0 + 디버프. 2코스트 기본(12)+보너스',
        },
      },
      {
        cells: {
          col0: 'CRD_004',
          col1: '바리케이드',
          col2: '레어',
          col3: '파워',
          col4: 3,
          col5: 0,
          col6: 0,
          col7: '-',
          col8: '방어도 유지',
          col9: '직접 효율 없음. 영구 효과로 후반 가치 급상승',
        },
      },
      {
        cells: {
          col0: 'CRD_005',
          col1: '섬광',
          col2: '언커먼',
          col3: '스킬',
          col4: 0,
          col5: 0,
          col6: 0,
          col7: '-',
          col8: '카드 1장 드로우',
          col9: '0코스트 유틸. 덱 압축+핸드 순환',
        },
      },
    ],
  },

  // 드랍 테이블
  {
    id: 'drop-table',
    name: '드랍 테이블 설계',
    description: '아이템 드랍 확률과 기대값. 파밍 효율 계산.',
    category: 'reward',
    genre: ['rpg', 'action', 'roguelike', 'fps'],
    context: '기대 보상 = (확률 × 평균 수량)의 합. 시간당 파밍 효율로 밸런스',
    keyMetrics: [
      '기대값 = 확률 × (최소+최대)/2',
      '시간당 효율 = 기대값 / 평균 클리어 시간',
      '희귀템 확률 1% 미만 시 천장 시스템 고려',
    ],
    columns: [
      { name: '소스', type: 'general' as ColumnType, width: 100, exportName: 'source' },
      { name: '소스레벨', type: 'general' as ColumnType, width: 80, exportName: 'sourceLevel' },
      { name: '아이템', type: 'general' as ColumnType, width: 110, exportName: 'item' },
      { name: '확률(%)', type: 'general' as ColumnType, width: 75, exportName: 'dropRate' },
      { name: '최소', type: 'general' as ColumnType, width: 55, exportName: 'minQuantity' },
      { name: '최대', type: 'general' as ColumnType, width: 55, exportName: 'maxQuantity' },
      { name: '기대값', type: 'formula' as ColumnType, width: 80, exportName: 'expectedValue' },
      { name: '클리어시간(초)', type: 'general' as ColumnType, width: 105, exportName: 'clearTime' },
      { name: '시간당기대값', type: 'formula' as ColumnType, width: 105, exportName: 'expectedValuePerHour' },
      { name: '설계의도', type: 'general' as ColumnType, width: 220, exportExcluded: true },
    ],
    sampleRows: [
      {
        cells: {
          col0: '슬라임',
          col1: 1,
          col2: 'HP 포션',
          col3: 30,
          col4: 1,
          col5: 2,
          col6: '=확률(%)/100*(최소+최대)/2',
          col7: 5,
          col8: '=기대값/클리어시간(초)*3600',
          col9: '초반 회복템. 기대값 0.45개. 시간당 324개',
        },
      },
      {
        cells: {
          col0: '슬라임',
          col1: 1,
          col2: '슬라임 젤리',
          col3: 50,
          col4: 1,
          col5: 3,
          col6: '=확률(%)/100*(최소+최대)/2',
          col7: 5,
          col8: '=기대값/클리어시간(초)*3600',
          col9: '제작 재료. 기대값 1개. 10개 수집에 50초',
        },
      },
      {
        cells: {
          col0: '오크 대장',
          col1: 5,
          col2: '레어 장비',
          col3: 5,
          col4: 1,
          col5: 1,
          col6: '=확률(%)/100*(최소+최대)/2',
          col7: 60,
          col8: '=기대값/클리어시간(초)*3600',
          col9: '엘리트 보상. 20회 처치에 1개 기대. 20분 파밍',
        },
      },
      {
        cells: {
          col0: '드래곤',
          col1: 10,
          col2: '전설 장비',
          col3: 1,
          col4: 1,
          col5: 1,
          col6: '=확률(%)/100*(최소+최대)/2',
          col7: 300,
          col8: '=기대값/클리어시간(초)*3600',
          col9: '1% 확률. 100회 클리어 기대. 약 8시간 파밍',
        },
      },
    ],
  },
];
